USE DB_DIONISIO_JUNIOR;

SELECT * FROM DB_T2_DIONISIO_JUNIOR.CLIENTE;
SELECT * FROM DB_T2_DIONISIO_JUNIOR.NOVELA;
SELECT * FROM DB_T2_DIONISIO_JUNIOR.ACTOR;
SELECT * FROM DB_T2_DIONISIO_JUNIOR.BROADCASTER;

SELECT NAME_NOVEL, YEAR_NOVEL
	FROM NOVELA
	ORDER BY YEAR_NOVEL DESC; /* Do mais novo para o mais antigo */

SELECT NAME_ACTOR, AGE_ACTOR
	FROM ACTOR
	ORDER BY AGE_ACTOR ASC; /* Do mais jovem para o mais velho */
    
SELECT NAME_NOVEL, GENRE_NOVEL
	FROM NOVELA
    ORDER BY NAME_NOVEL ASC; /* DE A a Z */
    
SELECT NAME_ACTOR, SALARY_ACTOR
	FROM ACTOR
    ORDER BY SALARY_ACTOR DESC; /* Do maior ao menor */
    
SELECT NAME_BROADCASTER
	FROM BROADCASTER
    ORDER BY FOUNDATION_YEAR_BROADCASTER ASC; /* DE A a Z */
