USE DB_DIONISIO_JUNIOR;
/*

boas práticas de nomenclatura

CREATE TABLE novela (
    id_novela INT AUTO_INCREMENT PRIMARY KEY,
    nome_novela VARCHAR(100) NOT NULL,
    ano_lancamento YEAR,
    genero VARCHAR(50),
    audiencia_media DECIMAL(10,2)
);

*/

CREATE TABLE CLIENTE ( 
	ID_COSTUMER INT AUTO_INCREMENT 
PRIMARY KEY,
		NAME_COSTUMER VARCHAR(100),
        TEL_COSTUMER VARCHAR(20),
        EMAIL_COSTUMER VARCHAR(100)
);

CREATE TABLE NOVELA ( 
	ID_NOVEL INT AUTO_INCREMENT 
PRIMARY KEY,
		NAME_NOVEL VARCHAR(100),
        YEAR_NOVEL YEAR,
        GENRE_NOVEL VARCHAR(100),
        AUDIENCE_NOVEL FLOAT(10,2)
);

CREATE TABLE ACTOR ( 
	ID_ACTOR INT AUTO_INCREMENT 
PRIMARY KEY,
		NAME_ACTOR VARCHAR(100),
        AGE_ACTOR TINYINT,
        CHARACTER_ACTOR VARCHAR(100),
        SALARY_ACTOR DECIMAL(10,2)
);

CREATE TABLE BROADCASTER (
    ID_BROADCASTER INT AUTO_INCREMENT 
    PRIMARY KEY,
		NAME_BROADCASTER VARCHAR(100),
		COUNTRY_BROADCASTER VARCHAR(20),
		FOUNDATION_YEAR_BROADCASTER YEAR
);
